Modify docker config to add base connector
drone/drone-kaniko pull request #115
Opened 2024-04-08 23:18 UTC by Aishwarya-Lad

Support to allow base images to be pulled from private registries for kaniko-docker.

Tested locally. End to end testing will be covered in another ticket. 

<img width="1643" alt="Screenshot 2024-04-08 at 4 17 59 PM" src="https://github.com/drone/drone-kaniko/assets/67022814/caa5a70c-7550-4774-bb7c-e2f54533d8af">

2024-04-11 06:21 UTC, raghavharness requested changes

2024-04-11 06:21 UTC, raghavharness commented on cmd/kaniko-docker/main.go
> +	dockerUsername := c.String("docker-username")
We can keep the variables name like `baseImageUsername` which makes it more clear. Similar for others

2024-04-11 06:21 UTC, raghavharness commented on cmd/kaniko-docker/main.go
>  		return errors.Wrap(err, "failed to write docker config file")
Let's use `docker.CreateDockerCfgFile` utility (or create different method) for this. This can be used by others (gar, acr) as well.

2024-04-24 03:01 UTC, raghavharness requested changes

2024-04-26 09:56 UTC, raghavharness requested changes

2024-04-26 09:56 UTC, raghavharness commented on cmd/kaniko-acr/main.go
> +	dockerConfig.CreateDockerConfig(credentials, dockerConfigPath)
we should return the error from `dockerConfig.CreateDockerConfig(credentials, dockerConfigPath)`

2024-04-26 09:56 UTC, raghavharness commented on cmd/kaniko-docker/main.go
> +	dockerConfig.CreateDockerConfig(credentials, dockerPath)
ditto

2024-04-26 09:56 UTC, raghavharness commented on cmd/kaniko-docker/main.go
> +func validateDockerCreds(username, password, registry string) error {
from where are we calling this method now ?

2024-04-26 09:56 UTC, raghavharness commented on cmd/kaniko-ecr/main.go
> +		dockerConfig.CreateDockerConfig(credentials, dockerConfigPath)
ditto

2024-04-26 09:56 UTC, raghavharness commented on cmd/kaniko-gar/main.go
> +	dockerConfig.CreateDockerConfig(credentials, dockerConfigPath)
ditto

2024-04-26 09:56 UTC, raghavharness commented on cmd/kaniko-gcr/main.go
> +	dockerConfig.CreateDockerConfig(credentials, dockerConfigPath)
ditto

2024-04-26 09:56 UTC, raghavharness commented on pkg/docker/config.go
> +		return errors.Wrap(err, "failed to read docker config json")
failed to serialise docker config

2024-04-26 10:05 UTC, raghavharness commented on cmd/kaniko-ecr/main.go
> +		return dockerConfig.CreateDockerConfig(credentials, dockerConfigPath)
If you do the create config here then it won't work. It should be outside of if else conditiom

2024-04-26 10:06 UTC, raghavharness commented on main
remove this bin file

2024-04-26 10:06 UTC, raghavharness commented on pkg/docker/config.go
> +		return errors.Wrap(err, fmt.Sprintf("failed to serialize docker config to path: %s", dockerPath))
You added message in wrong place

2024-04-26 10:07 UTC, raghavharness commented on cmd/kaniko-acr/main.go
> +	return nil
return dockerConfig.CreateDockerConfig(credentials, dockerConfigPath)

2024-04-26 10:57 UTC, raghavharness approved these changes

2024-04-26 19:53 UTC, jamie-harness approved these changes

2024-04-26 19:54 UTC, merged

2024-04-26 19:54 UTC, jamie-harness commented
Merged. Please confirm regression risk and post testings